name: Deploy Serverless App

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      stage:
        description: "Environment to deploy (dev, qa, prod)"
        required: false
        default: "dev"

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Install Dependencies
        run: npm ci

      - name: 🔨 Compile TypeScript
        run: npm run build

      - name: 🚀 Deploy via Serverless
        run: npx serverless deploy --stage ${{ github.event.inputs.stage || 'dev' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
