name: Deploy Serverless App

on:
  push:
    branches: [main]  # Adjust this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Prepare Deployment Package
        run: |
          mkdir -p .build
          cp -r dist package.json package-lock.json .build/
          cd .build
          npm ci --only=production
          zip -r ../lambda-package.zip .

      - name: Deploy to AWS via Serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }} 
        run: npx serverless deploy
